version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: file_server_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: NodeJsDB
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: NodeJsDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
    container_name: file_server_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mysql_data:
