version: '3.8'

services:
  backend:
    build:
      context: ./backend/TP_NodeJS
      dockerfile: Dockerfile
    container_name: file_server_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: NodeJsDB
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: NodeJsDB
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build:
      context: ./frontend/tp_nodejs_front
      dockerfile: Dockerfile
    container_name: file_server_frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  mysql_data:
